from datetime import datetime
import requests
import os
from dotenv import load_dotenv
import requests

# Dictionary mapping dates to holidays
holidays_by_date = {
    '2025-01-06': ['Epiphany', 'Guru Gobind Singh Gurpurab'],
    '2025-01-07': ['Coptic Orthodox Christmas'],
    '2025-01-14': ['Pongal', 'Mahayana New Year'],
    '2025-02-15': ['Parinirvana', 'Lupercalia'],
    '2025-02-26': ['Maha Shivaratri'],
    '2025-03-14': ['Holi', 'Hola Mohalla'],
    '2025-05-05': ['Buddha’s Birthday'],
    '2025-05-16': ['Lag BaOmer'],
    '2025-05-28': ['Ascension of Baha’u’llah'],
    '2025-06-02': ['Shavuot begins'],
    '2025-06-05': ['The Hajj begins'],
    '2025-06-07': ['Eid-al-Adha begins'],
    '2025-06-08': ['Pentecost (Whit Sunday)'],
    '2025-06-19': ['Feast of Corpus Christi'],
    '2025-07-23': ['Birthday of Haile Selassie'],
    '2025-07-24': ['Pioneer Day'],
    '2025-08-16': ['Krishna Janmashtami begins'],
    '2025-08-21': ['Paryushana begins'],
    '2025-08-27': ['Ganesh Chaturthi', 'Paryushana Festival'],
    '2025-09-05': ['Mawlid al-Nabi'],
    '2025-09-11': ['Nayrouz'],
    '2025-09-23': ['Rosh Hashanah begins'],
    '2025-10-07': ['Sukkot begins'],
    '2025-11-21': ['The Entrance of the Theotokos into the Temple'],
    '2025-12-06': ['Saint Nicholas Day'],
    '2025-12-15': ['Hanukkah begins'],
    '2025-01-01': ['Iroquois Midwinter Ceremony'],
    '2025-01-27': ['Laylat al-Isra wa al-Mi\'raj'],
    '2025-01-30': ['Sadeh'],
    '2025-02-01': ['Imbolc'],
    '2025-02-02': ['Vasant Panchami', 'Imbolc', 'Candlemas'],
    '2025-02-12': ['Tu B\'Shevat'],
    '2025-02-14': ['Laylat al-Bara\'ah'],
    '2025-03-01': ['Nineteen Day Fast', 'Eagle Dances', 'Ramadan'],
    '2025-03-03': ['Great Lent'],
    '2025-03-05': ['Ash Wednesday'],
    '2025-03-13': ['Purim'],
    '2025-03-16': ['Ghambar Hamaspathmaedem'],
    '2025-03-20': ['Naw Ruz (Bahá’í)', 'Ostara'],
    '2025-03-21': ['Naw Ruz (Zoroastrianism)'],
    '2025-03-26': ['Birthday of Prophet Zarathustra (Khordad Sal)'],
    '2025-03-27': ['Laylat al-Qadr'],
    '2025-03-30': ['Eid al-Fitr'],
    '2025-03-31': ['Eid al-Fitr', 'Hydesville Day'],
    '2025-04-19': ['Great Lent'],
    '2025-04-06': ['Anniversary of the Founding of the Church', 'Ramanavami'],
    '2025-04-10': ['Mahavir Jayanti'],
    '2025-04-12': ['Passover', 'The Memorial of Jesus’ Death'],
    '2025-04-13': ['Palm Sunday', 'Passover begins'],
    '2025-04-14': ['Vaisakhi'],
    '2025-04-17': ['Holy Thursday/Maundy Thursday'],
    '2025-04-18': ['Good Friday', 'Holy Friday'],
    '2025-04-20': ['Easter Sunday', 'Easter Sunday (Pascha)', 'Ridvan', 'Passover'],
    '2025-04-23': ['Yom Hashoah'],
    '2025-04-30': ['Ghambar Maidyozarem', 'Hexennacht'],
    '2025-05-01': ['Beltane', 'Hopi Kachina Dances', 'Ridvan'],
    '2025-05-04': ['Ghambar Maidyozarem'],
    '2025-05-12': ['Wesak (Buddha Day)', 'Vesak'],
    '2025-05-22': ['Declaration of the Bab'],
    '2025-05-27': ['Ascension of Baha\'u\'llah'],
    '2025-05-31': ['Hopi Kachina Dances'],
    '2025-06-16': ['Martyrdom of Guru Arjan Dev Ji'],
    '2025-06-20': ['Litha'],
    '2025-06-26': ['First of Muharram (Ra\'s al-Sanat Al Hijrivah)'],
    '2025-06-27': ['Martyrdom of the Prophet Joseph Smith and his Brother Hyrum'],
    '2025-06-29': ['Ghambar Maidyoshem'],
    '2025-07-01': ['Ghambar Maidyoshem', 'Green Corn Ceremony', 'Mescalero Apache Mountain Spirit Dances'],
    '2025-07-03': ['Ghambar Maidyoshem'],
    '2025-07-05': ['Ashurah'],
    '2025-07-31': ['Green Corn Ceremony', 'Mescalero Apache Mountain Spirit Dances'],
    '2025-07-09': ['Martyrdom of the Bab'],
    '2025-07-10': ['Dharma Day (Asalha Puja)'],
    '2025-08-01': ['Green Corn Ceremony', 'Hopi Snake Dance', 'Iroquois Green Corn Ceremony', 'Lughnasadh', 'Lammas/Lughnasa'],
    '2025-08-31': ['Green Corn Ceremony', 'Hopi Snake Dance', 'Iroquois Green Corn Ceremony'],
    '2025-08-02': ['Tisha B\'Av'],
    '2025-08-08': ['Raksha Bandhan'],
    '2025-08-15': ['Assumption of the Blessed Virgin Mary', 'Dormition of the Theotokos', 'Krishna Janmashtami', 'Feast of the Assumption'],
    '2025-08-19': ['Paryushana Festival'],
    '2025-08-26': ['Ganesh Chaturthi'],
    '2025-08-28': ['Das Laxana Festival'],
    '2025-09-01': ['Iroquois Green Corn Ceremony', 'Jicarilla Apache Ghost Dance'],
    '2025-09-04': ['Mawlid an-Nabi'],
    '2025-09-06': ['Das Laxana Festival'],
    '2025-09-30': ['Iroquois Green Corn Ceremony', 'Jicarilla Apache Ghost Dance'],
    '2025-09-08': ['Feast of the Nativity of the Theotokos'],
    '2025-09-12': ['Ghambar Paitishem'],
    '2025-09-16': ['Ghambar Paitishem'],
    '2025-09-22': ['Mabon', 'Navaratri', 'Rosh Hashanah', 'Navratri begins'],
    '2025-09-24': ['Rosh Hashanah'],
    '2025-10-01': ['Cherokee Great New Moon Festival'],
    '2025-10-02': ['Dussehra (Vijaya Dashami)', 'Yom Kippur', 'Navaratri'],
    '2025-10-06': ['Sukkot'],
    '2025-10-12': ['Ghambar Ayathrem'],
    '2025-10-13': ['Ghambar Ayathrem', 'Shemini Atzeret', 'Sukkot'],
    '2025-10-14': ['Simchat Torah'],
    '2025-10-16': ['Ghambar Ayathrem'],
    '2025-10-20': ['Diwali (Dipavali)', 'Installation of Granth Sahib Ji as Guru', 'Diwali'],
    '2025-10-21': ['Diwali/Mahavir Nirvana'],
    '2025-10-22': ['Birth of the Bab'],
    '2025-10-23': ['Birth of Baha\'u\'llah'],
    '2025-10-31': ['Reformation Day', 'Samhain', 'Cherokee Great New Moon Festival', 'Halloween (TST)'],
    '2025-11-01': ['All Saints\' Day'],
    '2025-11-02': ['All Souls\' Day'],
    '2025-11-05': ['Guru Nanak\'s Birthday'],
    '2025-11-24': ['Day of the Covenant', 'Martyrdom of Guru Tegh Bahadur Ji', 'Martyrdom of Guru Tegh Bahadur Sahib'],
    '2025-11-27': ['Ascension of \'Abdu\'l-Baha'],
    '2025-11-30': ['First Sunday of Advent'],
    '2025-12-01': ['Shalako Kachina Ceremony'],
    '2025-12-08': ['Bodhi Day (Rohatsu)', 'Feast of the Immaculate Conception of Mary'],
    '2025-12-12': ['Feast of Our Lady of Guadalupe'],
    '2025-12-14': ['Hanukkah'],
    '2025-12-21': ['Yule'],
    '2025-12-22': ['Hanukkah'],
    '2025-12-25': ['Christmas', 'Feast of the Nativity of Jesus Christ', 'Sol Invictus'],
    '2025-12-26': ['Death of the Prophet Zarathustra'],
    '2025-12-31': ['Ghambar Maidyarem', 'Shalako Kachina Ceremony'],
    '2026-01-01': ['Ghambar Maidyarem', 'Iroquois Midwinter Ceremony'],
    '2026-01-04': ['Ghambar Maidyarem'],
    '2026-01-31': ['Iroquois Midwinter Ceremony'],
    '2025-07-25': ['Unveiling Day'],

}
# Add more dates and holidays as needed


# Dictionary mapping holiday names to their descriptions, these can be re-used in future years and descriptions modified as appropriate
holiday_descriptions = {
    'Epiphany': ['Christianity', 'Celebrates the visit of the Magi to the baby Jesus.'],
    'Guru Gobind Singh Gurpurab': ['Sikhism', 'Celebrates the birth of Guru Gobind Singh, the Sikhs’ 10th master and teacher.'],
    'Coptic Orthodox Christmas': ['Coptic Orthodox Christianity', 'Marks the birth of Jesus Christ according to the Julian calendar.'],
    'Pongal': ['Hinduism', 'A harvest festival thanking the Sun God for agricultural abundance.'],
    'Mahayana New Year': ['Buddhism', 'Celebrates the Buddhist New Year in Mahayana traditions.'],
    'Candlemas': ['Christianity', 'Commemorates the presentation of Jesus at the temple.'],
    'Parinirvana': ['Buddhism', 'Marks the death of Buddha and his attainment of final Nirvana.'],
    'Maha Shivaratri': ['Hinduism', 'A major Hindu festival celebrating Lord Shiva.'],
    'Ramadan begins': ['Islam', 'A holy month of fasting, prayer, and reflection for Muslims.'],
    'Holi': ['Hinduism', 'The festival of colors, celebrating the arrival of spring.'],
    'Hola Mohalla': ['Sikhism', 'A Sikh festival featuring martial arts, poetry, and community gatherings.'],
    'Naw-Ruz': ['Baha’i', 'The Baha’i New Year, celebrated with joy and festivities.'],
    'The Memorial of Jesus’ Death': ['Jehovah’s Witnesses', 'Commemorates the death of Jesus Christ.'],
    'Passover begins': ['Judaism', 'Celebrates the liberation of the Israelites from Egyptian slavery.'],
    'Easter': ['Christianity', 'Celebrates the resurrection of Jesus Christ.'],
    'Buddha’s Birthday': ['Buddhism', 'Celebrates the birth of Siddhartha Gautama, who became the Buddha.'],
    'Vesak': ['Buddhism', 'Commemorates the birth, enlightenment, and death of Buddha.'],
    'Lag BaOmer': ['Judaism', 'A minor Jewish holiday celebrated with bonfires and festivities.'],
    'Ascension of Baha’u’llah': ['Baha’i', 'Marks the passing of Baha’u’llah, the founder of the Baha’i Faith.'],
    'Shavuot begins': ['Judaism', 'Celebrates the giving of the Torah at Mount Sinai.'],
    'The Hajj begins': ['Islam', 'The annual pilgrimage to Mecca, one of the Five Pillars of Islam.'],
    'Eid-al-Adha begins': ['Islam', 'The Festival of Sacrifice, commemorating Ibrahim’s willingness to sacrifice his son.'],
    'Pentecost (Whit Sunday)': ['Christianity', 'Commemorates the descent of the Holy Spirit upon the apostles.'],
    'Feast of Corpus Christi': ['Christianity', 'A Catholic feast honoring the presence of Jesus in the Eucharist.'],
    'Ashura': ['Islam', 'Observed differently by Sunni and Shia Muslims, commemorating significant historical events.'],
    'Birthday of Haile Selassie': ['Rastafarianism', 'Celebrates the birth of Emperor Haile Selassie, seen as a divine figure.'],
    'Lughnasadh': ['Pagan and Wiccan', 'A festival marking the beginning of the harvest season.'],
    'Feast of the Assumption': ['Christianity', 'Celebrates the belief that Mary was taken into Heaven.'],
    'Krishna Janmashtami begins': ['Hinduism', 'Celebrates the birth of Lord Krishna.'],
    'Paryushana begins': ['Jainism', 'A significant Jain festival focusing on fasting and reflection.'],
    'Mawlid al-Nabi': ['Islam', 'Celebrates the birth of the Prophet Muhammad.'],
    'Nayrouz': ['Coptic Christianity', 'The Coptic New Year, marking the beginning of the Egyptian calendar.'],
    'Navratri begins': ['Hinduism', 'A nine-night festival dedicated to the goddess Durga.'],
    'Rosh Hashanah begins': ['Judaism', 'The Jewish New Year, a time of reflection and renewal.'],
    'Sukkot begins': ['Judaism', 'The Feast of Booths, commemorating the Israelites’ journey in the desert.'],
    'Diwali': ['Hinduism, Sikhism, Jainism', 'The Festival of Lights, celebrating victory over darkness.'],
    'Birthday of the Bab': ['Baha’i', 'Celebrates the birth of the Bab, the forerunner of Baha’u’llah.'],
    'All Saints’ Day': ['Christianity', 'A day to honor all saints, known and unknown.'],
    'All Souls’ Day': ['Christianity', 'A day of prayer for the faithful departed.'],
    'The Entrance of the Theotokos into the Temple': ['Eastern Orthodox Christianity', 'Celebrates Mary’s dedication to the temple as a child.'],
    'Martyrdom of Guru Tegh Bahadur Sahib': ['Sikhism', 'Commemorates the martyrdom of Guru Tegh Bahadur for religious freedom.'],
    'Advent': ['Christianity', 'The period of preparation for the birth of Jesus Christ.'],
    'Saint Nicholas Day': ['Christianity', 'Honors Saint Nicholas, the inspiration for Santa Claus.'],
    'Bodhi Day': ['Buddhism', 'Commemorates the enlightenment of Siddhartha Gautama, the Buddha.'],
    'Hanukkah begins': ['Judaism', 'The Festival of Lights, celebrating the rededication of the Second Temple.'],
    'Laylat al-Isra wa al-Mi\'raj': ['Islam','Commemorates the ascension (al-Mi\'raj) of the Prophet to heaven following his night journey (al-Isra\') from Mecca to Jerusalem and his ascent to heaven and return the same night. Begins at sundown.'],
    'Sadeh': ['Zoroastrianism','An Iranian mid-winter celebration observed by the kindling of fire. Meaning “one-hundred,” Sadeh marks 50 days (100 days and nights) before Naw-Ruz.'],
    'Imbolc': ['Wicca/Paganism','The first fertility festival, celebrating the approach of spring and the growth of light in the darkness.'],
    'Vasant Panchami': ['Hinduism','One of many festivals to honor the advent of spring, this day is celebrated particularly in North India, where it is associated with Saraswati, the goddess of learning; however, it also retains connection with the goddess Lakshmi.'],
    'Tu B\'Shevat': ['Judaism','A mid-winter celebration of the new year of the trees. Sometimes referred to as “Jewish Earth Day.”'],
    'Laylat al-Bara\'ah': ['Islam','Begins at sundown. (Night of Repentance) On this night, God approaches the Earth to call humanity and to grant forgiveness of sins. Observed on the 14th day of the lunar month of Sha\'ban.'],
    'Nineteen Day Fast': ['Baha’i','A designated 19-day period of fasting each year immediately before the Bahá’í New Year. The fasting is seen as a period of spiritual preparation and regeneration for the new year ahead.'],
    'Eagle Dances': ['Indigenous American','Pueblo peoples (Arizona) perform Eagle dances dramatizing the relationship of their communities with the Sky-World.'],
    'Ramadan': ['Islam','The Holy Month of Ramadan is the month of fasting during which Muslims who are physically able do not eat or drink from the first sign of dawn until sunset in honor of the first revelations to the Prophet Muhammad. The evening meal is celebrated with family.'],
    'Great Lent': ['Christianity-Orthodox', 'In Orthodox churches, the first day of Lent marks the beginning of the Great Fast, the final six weeks of a 10-week period leading up to Holy Week and Easter (Pascha). It is a time of repentance and sacrifice in preparation for Easter.'],
    'Ash Wednesday': ['Christianity-Protestant, Christianity-Roman Catholic','A special day of repentance observed by Protestant and Roman Catholic Christians to mark the beginning of Lent, the 40-day period (excluding Sundays) of prayer, repentance, and self-denial preceding Easter. The name derives from the practice of marking of the faithful with ashes to signify penitence.'],
    'Purim': ['Judaism', 'Celebrates the rescue of the Jews of ancient Persia from a plot to destroy them as related in the Book of Esther, which is read at this time. Purim is a joyous holiday, celebrated by wearing of costumes, giving gifts to friends, giving to the poor, and socializing. Preceded by the Fast of Esther, Purim is a day of feasting. Begins at sundown.'],
    'Ghambar Hamaspathmaedem': ['Zoroastrianism', 'Celebrates the creation of human beings and honors the souls of the deceased.'],
    'Naw Ruz (Bahá’í)': ['Baha’i', 'The seventh greatest festival, “New Day” is the first day of the Zoroastrian/Persian and Bahá’í New Year. It falls on the spring equinox and symbolizes the renewal of the world after the winter.'],
    'Ostara': ['Wicca/Paganism','Vernal Equinox, celebrating the equivalence of light and dark and the arrival of Spring.'],
    'Naw Ruz (Zoroastrianism)': ['Zoroastrianism', 'The seventh greatest festival, "New Day" is the first day of the Zoroastrian/Persian and Bahá’í New Year. It falls on the spring equinox and symbolizes the renewal of the world after the winter. For Zoroastrians, Naw Ruz also celebrates the creation of fire that is symbolic of Asha, or righteousness. It is also the day on which Zarathustra received his revelation.'],
    'Birthday of Prophet Zarathustra (Khordad Sal)': ['Zoroastrianism','The anniversary of the birth of the founder of the Zoroastrian faith.'],
    'Laylat al-Qadr': ['Islam','The Night of Power or Destiny commemorates the first revelation of the Qur\'an (the Islamic scriptures) to Prophet Muhammad in 610 CE.'],
    'Eid al-Fitr': ['Islam','Also known as the Festival of the Breaking of the Fast. One of the two main Islamic festivals (the other is Eid al-Adha), this day celebrates the end of Ramadan, the month of fasting. It comes on the first day of the next lunar month, Shawal.'],
    'Hydesville Day': ['Spiritualism','On this date in 1848, the discarnate soul of Charles B. Rosna communicated via the mediumship of the Fox sisters, heralding the advent of Modern Spiritualism.'],
    'Anniversary of the Founding of the Church': ['Latter Day Saints','Annual World General Conference of the Church held on Saturday and Sunday closest to this date each year.'],
    'Ramanavami': ['Hinduism','Celebrates the birthday of Rama, the seventh incarnation of the God Vishnu. The Ramayana, one of the Hindu epics that tells the story of Rama, is read during the previous eight days.'],
    'Mahavir Jayanti': ['Jainism','Celebrates the birthday of Lord Mahavira. Born with the name Vardhamana in ca. 599 BCE, he was later given the titles of honor, Mahavira ("Great Hero") and Jina ("Conqueror" or "Victor"), a title applied also to the other Tirthankaras.'],
    'Passover': ['Judaism','Passover commemorates the deliverance of the Israelites from slavery in Egypt. It is celebrated for eight days with special prayers and symbolic foods at home, starting with the Seder, a ritual meal that re-enacts that ancient deliverance and emphasizes the freedom of the Jews under the guidance of God. The first two and the last two days are holidays.'],
    'Palm Sunday': ['Christianity-Orthodox, Christianity-Protestant, Christianity-Roman Catholic','Celebrates the entry of Jesus into Jerusalem, marking the beginning of Holy Week that culminates in Easter or Pascha. In some churches, Palm Sunday is combined with the anticipation of Christ\'s death and so is also known as "Passion Sunday." Orthodox Christians often observe this Sunday on a date different from the date on which Protestant and Roman Catholics observe it.'],
    'Vaisakhi': ['Sikhism and Hinduism','Occurs on the first day of the solar year. It is primarily an agricultural festival, celebrating the harvest, and is especially important in North India. It is named after the month Vaisakh. For Sikhs, it is also the anniversary of the creation of the Khalsa (the "Brotherhood of the Pure") in 1699 by Guru Gobind Singh.'],
    'Holy Thursday/Maundy Thursday': ['Christianity-Orthodox, Christianity-Protestant, Christianity-Roman Catholic','Commemorates the institution of the Lord\'s Supper/the Eucharist by Jesus prior to his arrest and execution. "Maundy" is derived from the Latin text of John 13:34, in which Jesus gives a mandatum novum ("new commandment"). The date observed by Protestants and Roman Catholics differs from the date observed by Orthodox Christians.'],
    'Good Friday': ['Christianity-Protestant, Christianity-Roman Catholic','Commemorates the Passion of Jesus Christ, i.e., his death by crucifixion. Observed as "Holy Friday" by Orthodox Christians.'],
    'Holy Friday': ['Christianity-Orthodox','The day that commemorates the Passion of Jesus Christ, i.e., his death by crucifixion. It is the Orthodox equivalent of "Good Friday."'],
    'Easter Sunday': ['Christianity-Protestant, Christianity-Roman Catholic','Celebrates the resurrection from death of Jesus Christ. It is the oldest and most important festival in the Christian year and initiates the 50-day period culminating in Pentecost. Protestant and Roman Catholic Christians often observe Easter on a different date than Orthodox Christians, but in some years they fall on the same day.'],
    'Easter Sunday (Pascha)': ['Christianity-Orthodox','Celebrates the resurrection from death of Jesus Christ. It is the oldest and most important festival in the Christian year and initiates the 50-day period culminating in Pentecost. Protestant and Roman Catholic Christians often observe Easter on a different date than Orthodox Christians, but in some years they fall on the same day.'],
    'Ridvan': ['Baha\'i','Commemorates the 12 days that Baha\'u\'llah spent in the Garden of Ridvan in the last days of his exile in Baghdad, during which time he proclaimed himself as the one announced by Bab. Work is suspended for the first, ninth, and twelfth days.'],
    'Yom Hashoah': ['Judaism','Memorializes the six million Jews who died as victims of the Nazis during World War II and emphasizes respect for human dignity. Its observance is not limited to Jews. Begins at sundown.'],
    'Ghambar Maidyozarem': ['Zoroastrianism','Celebrates the creation of the sky and harvesting of the winter crop.'],
    'Beltane': ['Wicca/Paganism','The final fertility festival, celebrating the Earth\'s fecundity and anticipating the power of the sun and the Earth in summer.'],
    'Hopi Kachina Dances': ['Indigenous American','These dances take place throughout late spring and early summer in which long lines of Kachina Dancers, representing various spirit-powers, perform in the open plazas of Hopi pueblos in Arizona.'],
    'Wesak (Buddha Day)': ['Buddhism','The commemoration of Buddha\'s birth, enlightenment, and parinirvana, celebrated on the day of the full moon of the sixth lunar month in Southeast Asian cultures. In Tibetan culture, Wesak commemorates only the enlightenment and parinirvana. The dates of this celebration vary significantly among Buddhist cultures and communities.'],
    'Declaration of the Bab': ['Baha\'i','Commemorates the day in 1844 on which he announced his identity as the "Bab" ("Gate"), the herald of the new age. Begins at sundown.'],
    'Ascension of Baha\'u\'llah': ['Baha\'i','Marks the anniversary of the death of the founder of the Baha\'i faith. Work is suspended on this day.'],
    'Ascension of Jesus (Protestant & Roman Catholic)': ['Christianity-Protestant, Christianity-Roman Catholic','The celebration of Jesus\' ascension into heaven and enthronement as universal sovereign. It comes 40 days after Easter. The date observed by Protestants and Roman Catholics is often different from the date observed by Orthodox Christians.'],
    'Ascension of Jesus (Orthodox)': ['Christianity-Orthodox','The celebration of Jesus\' ascension into heaven and enthronement as universal sovereign. It comes 40 days after Easter. The date observed by Protestants and Roman Catholics is often different from the date observed by Orthodox Christians, but in some years they fall on the same day.'],
    'Shavuot': ['Judaism','Shavuot (or "Feast of Weeks") marks the conclusion of the seven weeks following Pesach (Passover). It is a celebration of the harvest of first fruits and commemorates the giving of the Torah and Commandments at Mount Sinai. Begins at sundown.'],
    'Eid al-Adha': ['Islam','(Festival of Sacrifice) One of the two main Islamic festivals (the other is Eid al-Fitr), this festival falls on the 10th day of the lunar month of Zul-Hijja and is the concluding act of pilgrimage to Mecca. In commemoration of Abraham’s faith, sheep, goats, and camels are offered to God, and the meat is distributed to the poor and needy. Eid al-Adha is observed whether or not one is on pilgrimage.'],
    'Pentecost': ['Christianity-Orthodox, Christianity-Protestant, Christianity-Roman Catholic','(Or Whitsunday) The commemoration of the coming of the Holy Spirit upon the disciples of Jesus following his ascension, Pentecost is considered the "birthday" of the Christian church (Acts 2:1-11). It comes 50 days after Easter (Pascha, Orthodox Easter). Roman Catholic and Protestant Christians often observe Pentecost on a different date from Orthodox Christians.'],
    'Insight Into Mindfulness: Buddhist Literacy for Mental Health and Wellness Professionals': ['Buddhism','A special event hosted by Harvard Divinity School focusing on Buddhist literacy, mindfulness, and mental health for professionals.'],
    'Martyrdom of Guru Arjan Dev Ji': ['Sikhism','(1563-1606) The fifth Guru, he built the Golden Temple of Amritsar to emphasize that the Sikh way was open to all, regardless of caste; the temple was constructed with doors facing all four directions. The first Sikh martyr, Arjan is also remembered for his contributions to and compilation of the Sikh Scriptures.'],
    'Litha': ['Wicca/Paganism','Summer Solstice, celebrating the longest day and the blessings of light as well as the beginning of the sun god\'s death. Begins at sundown.'],
    'First of Muharram (Ra\'s al-Sanat Al Hijrivah)': ['Islam','The first day of the first month of the Islamic year. This day commemorates the Hijra ("migration") of Muhammad and his followers from Mecca to Medina in 622 C.E., where the first Islamic community was established. Begins at sundown.'],
    'Martyrdom of the Prophet Joseph Smith and his Brother Hyrum': ['Latter Day Saints','The Prophet Joseph Smith and his brother Hyrum were assassinated in 1844 while incarcerated in Carthage, Illinois.'],
    'Ghambar Maidyoshem': ['Zoroastrianism','Celebrates the creation of water, the sowing of the summer crop, and the harvesting of grain.'],
    'Mescalero Apache Mountain Spirit Dances': ['Indigenous American','New Mexico. Also called the Crown Dance.'],
    'Ashurah': ['Islam','For Sunni Muslims, it is a voluntary fast day. Many important events are believed to have occurred on this day, such as Noah’s leaving the Ark and the freedom and departure of the Children of Israel from Egypt. For Shi’i Muslims, it is a time of mourning commemorating the martyrdom of Husain (the grandson of the Prophet Muhammad) on the 10th day of the lunar month of Muharram.'],
    'Martyrdom of the Bab': ['Baha\'i','Anniversary of the martyrdom of the Bab, the forerunner of Baha’u’llah, in 1850. Work is suspended on this day.'],
    'Dharma Day (Asalha Puja)': ['Buddhism','Commemorates the Buddha’s first teaching following his enlightenment. The date and name of this Buddhist celebration varies significantly among cultures and communities.'],
    'Pioneer Day': ['Latter Day Saints','Mormon observance of the arrival of Brigham Young at the site of Salt Lake City, Utah, in 1847.'],
    'Green Corn Ceremony': ['Indigenous American','A time of renewal and purification that involves fasting and dances, and for some, participation in sweat lodge rituals.'],
    'Hopi Snake Dance': ['Indigenous American','A sixteen-day purification ceremony which includes the gathering and blessing of snakes.'],
    'Lammas/Lughnasa': ['Wicca/Paganism','The first harvest festival, celebrating the sacrifices of the Earth, the sun for the harvest, and the diminishing strength of summer.'],
    'Tisha B\'Av': ['Judaism','A day of communal mourning of the destruction of the First and Second Temples. Tisha B’Av is the saddest day of the Jewish calendar and is recognized by fasting.'],
    'Raksha Bandhan': ['Hinduism''Also abbreviated to Rakhi, it is the Hindu festival that celebrates brotherhood and love. It is celebrated on the full moon in the month of Sravana in the lunar calendar.'],
    'Assumption of the Blessed Virgin Mary': ['Christianity-Protestant, Christianity-Roman Catholic','Commemorates the assumption of Mary, mother of Jesus, into heaven.'],
    'Dormition of the Theotokos': ['Christianity-Orthodox','Commemorates the death of Mary, the mother of Jesus.'],
    'Krishna Janmashtami': ['Hinduism','Celebrates the birthday of Krishna. According to the Hindu epics, Krishna was the eighth incarnation of the God Vishnu, opposed to the demon Kansa, who was responsible for the increase of evil in the world. Worship of Krishna is characteristically expressed in dance and song.'],
    'Paryushana Festival': ['Jainism','Considered the holiest period of the year, these eight days are marked for Jains by fasting, meditation, prayer, and public readings of the life story of Lord Mahavira. Observed especially by the followers of the Shvetambara sect, Paryushana concludes on Samvatsari, the most solemn occasion of self-scrutiny and forgiveness. On this day, Jains ask for forgiveness from their relatives and friends for any offense they may have committed by deed, word, or thought.'],
    'Ganesh Chaturthi': ['Hinduism','A celebration of Ganesh’s birthday, one of the major Hindu deities. Ganesh, who has the head of an elephant, is the God of Success and is invoked at the beginning of all new undertakings.'],
    'Das Laxana Festival': ['Jainism','A 10-day festival that is considered to be a holy convocation. During these days, Jains impose some restraints on their daily activities by fasting, meditation, and prayer. The last day of Paryushana is the most solemn occasion of forgiveness and the examination of one’s own thoughts and feelings. On this day, Jains ask for forgiveness from their relatives and friends for any offense they may have committed by deed, word, or thought.'],
    'Iroquois Green Corn Ceremony': ['Indigenous American','A time of renewal involving fasting, dances, offerings, and readings from the code of Handsome Lake.'],
    'Jicarilla Apache Ghost Dance': ['Indigenous American','A traditional ceremony held in New Mexico.'],
    'Mawlid an-Nabi': ['Islam','The birthday of the Prophet Muhammad.'],
    'Feast of the Nativity of the Theotokos': ['Christianity-Orthodox','Celebrates the belief that Mary, mother of Jesus, was born without sin.'],
    'Ghambar Paitishem': ['Zoroastrianism','Celebrates the creation of the Earth and the harvesting of the summer crop.'],
    'Mabon': ['Wicca/Paganism','Autumnal Equinox and the second harvest festival, celebrating the equivalence of light and dark, the arrival of Autumn, and thanksgiving for the Earth’s bounty.'],
    'Navaratri': ['Hinduism','A nine-night (nav-rat) celebration of nine auspicious forms of Shakti/Devi (feminine divine power/the Goddess).'],
    'Rosh Hashanah': ['Judaism','The Jewish New Year and the anniversary of the creation of the world, Rosh Hashanah is the first of the Ten Days of Awe (also known as the Ten Days of Repentance) that conclude on Yom Kippur. It marks the beginning of the holiest time of the year for Jews.'],
    'Cherokee Great New Moon Festival': ['Indigenous American','October marks the beginning of the new year for the Cherokee people.'],
    'Dussehra (Vijaya Dashami)': ['Hinduism','The concluding day of a 10-day festival honoring various goddesses, especially Durga, and Lord Rama, a manifestation of the God Vishnu. The 10-day festival is known as Navaratri (“nine nights”) and Durga Puja (“worship of Durga”). Its pervading theme is the victory of good over evil. Vijaya greetings are sent to friends and relatives.'],
    'Yom Kippur': ['Judaism','The conclusion of the 10 Days of Awe, Yom Kippur is the holiest and most solemn of all days in the Jewish year. It is characterized by repentance, fasting, and forgiveness.'],
    'Sukkot': ['Judaism','An eight-day Jewish festival of booths (or tabernacles) and the fall harvest. The name refers to the booths (sukkot) used by Israelites during desert wanderings and constructed in the fields during the harvest season. It is a time of thanksgiving for God’s presence in creation and among the Jewish people. The Eighth Day (Shemini Atzeret) is considered both the end of Sukkot and a distinct festival.'],
    'Ghambar Ayathrem': ['Zoroastrianism','Celebrates the creation of plants, the sowing of the winter crop, and the return of herds from pasture.'],
    'Shemini Atzeret': ['Judaism','See Sukkot.'],
    'Simchat Torah': ['Judaism','Joyous festival in which the annual cycle of the reading of the Torah in the synagogue is completed and its first book begun again. The celebration typically includes singing, dancing, and marching with Torah scrolls.'],
    'Diwali (Dipavali)': ['Hinduism','Perhaps the most popular of all Hindu festivals, also known as the Festival of Lights, it is dedicated to the Goddess Kali in Bengal and to Lakshmi, the Goddess of Wealth, in the rest of India. As with several other festivals, Diwali is associated with one of the stories about the destruction of evil by Vishnu in one of his many manifestations.'],
    'Installation of Granth Sahib Ji as Guru': ['Sikhism','This day celebrates Gobind Singh Ji’s passing on guru-ship to Scripture, henceforth known as the Guru Granth Sahib. (1708 C.E.)'],
    'Diwali/Mahavir Nirvana': ['Jainism','See Diwali. In Jainism, where the festival is also known as Mahavira Nirvana, Diwali celebrates the attainment of Moksa by Lord Mahavira. A burning lamp symbolizes the “light of knowledge” that dispels the darkness of delusion and ignorance.'],
    'Birth of the Bab': ['Baha\'i','The anniversary of the birth of the Bab, the herald of the new age for Bahá’ís. The Shrine of the Bab in Haifa, Israel, is part of the World Center of the Bahá’í faith.'],
    'Birth of Baha\'u\'llah': ['Baha\'i','The anniversary of the birth of Baha’u’llah, the founder of the Bahá’í faith. Work is suspended on this day.'],
    'Reformation Day': ['Christianity-Protestant','Commemorates the beginning of the Protestant Reformation of Christianity with Martin Luther’s challenge to the Roman church in the 16th century C.E.'],
    'Samhain': ['Wicca/Paganism','The New Year and the final harvest festival, celebrating the last gifts of the Earth before winter and the return of the spirits of the dead.'],
    'All Saints\' Day': ['Christianity-Protestant, Christianity-Roman Catholic','Christian celebration of the lives of all the saints, especially those not having a special day; Orthodox churches observe the day in mid-summer.'],
    'All Souls\' Day': ['Christianity-Roman Catholic','Catholic Christian observance in memory of all the faithful who are deceased. In some Latin cultures, this day is known as “The Day of the Dead.”'],
    'Guru Nanak\'s Birthday': ['Sikhism','Observes the birth of the founder of the Sikh religion in 1469 C.E. The first of the Ten Gurus, Guru Nanak was born in 1469 C.E. An accomplished poet, 974 of his hymns are part of the Guru Granth Sahib.'],
    'Day of the Covenant': ['Baha\'i','Celebrates the anniversary of the appointment of ’Abdu’l-Bahá, the son of Baha’u’llah, as the Center of the Covenant.'],
    'Martyrdom of Guru Tegh Bahadur Ji': ['Sikhism','This day commemorates the martyrdom of Guru Tegh Bahadur Ji (1621–1675), the ninth of the Ten Sikh Gurus. He is remembered not only for his defense of the Sikh faith, but also of Hinduism and of religious liberty.'],
    'Ascension of \'Abdu\'l-Baha': ['Baha\'i','Commemorates ’Abdu’l-Bahá’s death.'],
    'First Sunday of Advent': ['Christianity-Protestant, Christianity-Roman Catholic','Period of four weeks in which Christians prepare for Christmas and meditate on the end of all time. In Western churches, the first Sunday of Advent marks the beginning of the Christian liturgical year.'],
    'Shalako Kachina Ceremony': ['Indigenous American','Held at Zuni Pueblo (New Mexico). Celebrates the end of the old and the beginning of the New Year and blesses the houses of the Pueblo erected during the year.'],
    'Bodhi Day (Rohatsu)': ['Buddhism','In the northern tradition, this is the anniversary of the Buddha’s Enlightenment, ca. 596 B.C.E. In the southern tradition, the Buddha’s Enlightenment is celebrated during Wesak. The dates and names of Buddhist celebrations vary significantly among cultures and communities.'],
    'Feast of the Immaculate Conception of Mary': ['Christianity-Roman Catholic','A feast day that celebrates the belief that Mary, mother of Jesus, was born without sin.'],
    'Feast of Our Lady of Guadalupe': ['Christianity-Roman Catholic','Commemorates the day on which the Guadalupana (the Virgin of Guadalupe) appeared to San Juan Diego and her image appeared on his tilma (apron). The miraculous roses Juan Diego found and carried to the Bishop took the form of the image of Mary exactly as she had appeared to him at the hill of Tepeyac.'],
    'Hanukkah': ['Judaism','Celebrated for eight days to commemorate the rededication of the Temple following the Jews’ victory over occupying forces in 165 B.C.E., which reestablished for a time their religious and political freedom.'],
    'Yule': ['Wicca/Paganism','Winter Solstice, celebrating the longest night and the blessings of darkness as well as the rebirth of the sun god.'],
    'Christmas': ['Christianity-Protestant, Christianity-Roman Catholic','Celebrates the anniversary of the birth (nativity) of Jesus. Dec. 25 is the date of this observance for Roman Catholic, Protestant, and many Orthodox Christian churches. In some Orthodox churches, Christmas falls on January 7.'],
    'Feast of the Nativity of Jesus Christ': ['Christianity-Orthodox','Celebrates the anniversary of the birth (nativity) of Jesus. December 25 is the date of this observance for Roman Catholic, Protestant, and many Orthodox Christian churches.'],
    'Death of the Prophet Zarathustra': ['Zoroastrianism','The anniversary of the death of the founder of the Zoroastrian faith.'],
    'Ghambar Maidyarem': ['Zoroastrianism','Celebrates the creation of animals. Zoroastrians are encouraged to remember their practice of the equitable sharing of food during this observance.'],
    'Iroquois Midwinter Ceremony': ['Indigenous American','A six-day curative rite in which false faces visit houses. Old fires are extinguished, and new fires are lit.'],
    'Lupercalia': ['The Satanic Temple','Celebration of bodily autonomy, sexual liberation, and reproduction. Based on the Roman festival of the same name, Lupercalia falls on February 15. In keeping with the ancient tradition, February 13th and 14th are observed as feast days leading up to the actual holiday. In The Satanic Temple, this is a "hail yourself" day, offering a parallel to the "others-centered" traditions of Sol Invictus.'],
    'Hexennacht': ['The Satanic Temple','Occasion honoring those who fell victim to superstition and pseudoscience, whether by witch hunt, Satanic panic, or other injustices. In Johann Wolfgang von Goethe\'s *Faust: A Tragedy* (1808), Mephisto and Faust attend the Walpurgisnacht revelry atop Mount Brocken. TST\'s Hexenacht is a solemn holiday to honor those who were victimized by superstition.'],
    'Unveiling Day': ['The Satanic Temple','Celebration of religious plurality and shedding archaic superstition. A centerpiece of the religious movement and an icon of modern Satanism, the Baphomet with Children statue was commissioned by The Satanic Temple in 2014 and created by Mark Porter with "respect for diversity and religious minorities" in mind. On July 25, 2015, The Satanic Temple unveiled Baphomet to a large crowd of devotees in Detroit, signaling the beginning of the new Satanic era. This milestone in Satanic history is celebrated as Unveiling Day.'],
    'Halloween (TST)': ['The Satanic Temple','A holiday to celebrate indulgence and embrace the darkness and its aesthetic. Halloween is consistently described as evil, demonic, and satanic by those steeped in religious dogma. Costumes, candy, and facing fears are to be embraced.'],
    'Sol Invictus': ['The Satanic Temple','Celebration of being unconquered by superstition and consistent in the pursuit and sharing of knowledge. The cult of Sol existed within Rome since its early days as a republic, and Invictus was an epithet used for Jupiter, Mars, and Apollo (among others). The festival celebrated these gods and may have also been used to celebrate the winter solstice.'],

}

# Environment Variable
load_dotenv()
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")


def send_discord_message(webhook_url, content):
    data = {
        'content': content
    }
    print(data)
    response = requests.post(webhook_url, json=data)
    if response.status_code == 204:
        print('Message sent successfully.')
    else:
        print(f'Failed to send message. Status code: {response.status_code}')

def notify_today_holidays(webhook_url):
    today_str = datetime.now().strftime('%Y-%m-%d')
    if today_str in holidays_by_date:
        holidays_today = holidays_by_date[today_str]
        for holiday in holidays_today:
            holiday_info = holiday_descriptions.get(holiday, ['Unknown', 'No description available.'])
            religion, description = holiday_info
            message = f"**{holiday} ({religion})**\n{description}"
            send_discord_message(webhook_url, message)
    else:
        print('No holidays today.')
notify_today_holidays(DISCORD_WEBHOOK_URL)

